name: premades_nn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^0.5.3
  flutter_easyrefresh: ^2.0.4
  dio: ^2.0.1
  path_provider: ^0.4.1 # 这是获取 安卓  IOS 文件缓存路径
  web_socket_channel: ^1.1.0
  provide: ^1.0.2
  photo_view: ^0.8.0  #目前仅支持安卓，后期需要优化
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  fluttertoast: ^3.1.3
  pull_to_refresh: ^1.5.7
  shared_preferences: ^0.5.3
  flutter_custom_dialog: ^1.0.14   # tost

  sqflite: 1.0.0 #本地数据库

  permission_handler: ^3.0.0 #权限

  azlistview: ^0.1.2 #排序列表

  event_bus: ^1.1.0 #消息总线

  city_pickers: ^0.1.20 #地区选择

  flutter_sound: ^1.1.5 #录音

  audioplayers: ^0.10.0 #播放录音

  extended_text_library: ^0.4.9 #拓展文本框可输入特殊字符 图片
  extended_text: any

  photo: ^0.4.5 #获取本地图片

  image: ^2.0.7 #图片解析

  connectivity: ^0.3.2 #网络监听

  image_picker: ^0.4.12+1 #图片选择  ios没有

  image_cropper: 1.1.0 #图片裁剪
  url_launcher: ^4.0.1 # 唤起第三方

  numberpicker: ^1.0.0 #日期选择
  date_format: ^1.0.6

  package_info: ^0.3.2+1 #配置信息获取

  flutter_webview_plugin: ^0.3.0 #webview

  flutter_html: ^0.11.1 #html解析

  encrypt: ^3.3.1   #rsa加密
  sharesdk_plugin: ^1.1.7

  flutter_local_notifications: ^0.4.4+2 #应用通知

  flutter_geetest: #极验证
    git: https://github.com/Joker-388/flutter-geetest.git

  flutter_custom_bottom_tab_bar: #tab bar
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git

  agora_rtc_engine: ^1.0.1
  flutter_downloader: ^1.3.4 #下载
  open_file: ^2.0.3   #打开apk
  ota_update: ^2.0.2
  install_plugin: ^2.0.1 #用于为Android安装APK; 并使用网址转到iOS的应用商店
  flutter_spinkit: ^4.1.1
  android_alarm_manager: ^0.4.1+6 #后台定时任务

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/dd.gif
    - images/cha.png
    - images/flash_page.png
    - images/go_back.png
    - images/icon_check.png
    - images/icon_uncheck.png
    - images/guide_1.png
    - images/guide_2.png
    - images/guide_3.png
    - images/guide_4.png
    - images/guide_5.png
    - images/icon_login_leigod.png
    - images/icon_boy.png
    - images/icon_game_choose.png
    - images/icon_game_normal.png
    - images/icon_girl.png
    - images/icon_message_choose.png
    - images/icon_message_normal.png
    - images/icon_mine_choose.png
    - images/icon_mine_normal.png
    - images/icon_safe.png
    - images/icon_service.png
    - images/icon_set.png
    - images/icon_share.png
    - images/icon_edit.png
    - images/icon_add.png
    - images/icon_message_helper.png
    - images/icon_system_message.png
    - images/emoji/e10001.png
    - images/emoji/e10002.png
    - images/emoji/e10003.png
    - images/emoji/e10004.png
    - images/emoji/e10005.png
    - images/emoji/e10006.png
    - images/emoji/e10007.png
    - images/emoji/e10008.png
    - images/emoji/e10009.png
    - images/emoji/e10010.png
    - images/emoji/e10011.png
    - images/emoji/e10012.png
    - images/emoji/e10013.png
    - images/emoji/e10014.png
    - images/emoji/e10015.png
    - images/emoji/e10016.png
    - images/emoji/e10017.png
    - images/emoji/e10018.png
    - images/emoji/e10019.png
    - images/icon_emoji.png
    - images/icon_emoji_on.png
    - images/icon_photo.png
    - images/icon_photo_on.png
    - images/icon_pic.png
    - images/icon_pic_on.png
    - images/icon_voice.png
    - images/icon_voice_on.png
    - images/icon_phone.png
    - images/icon_phone_on.png
    - images/btn_bo.png
    - images/btn_delete.png
    - images/btn_voice.png
    - images/bubble_myself_default.png
    - images/bubble_others_default.png
    - images/icon_pause.png
    - images/icon_play.png
    - images/icon_voice_phone.png
    - images/icon_more.png
    - images/no_list.png
    - images/image_default.png
    - images/head_default.png
    - images/icon_member_add.png
    - images/icon_member_remove.png
    - images/icon_disable.png
    - images/see.jpg
    - images/no_see.jpg
    - images/mascot.png
    - images/no_speak.png
    - images/no_all.png
    - images/no_write.png
    - images/room_listen.png
    - images/room_share.png
    - images/room_speak.png
    - images/room_write.png
    - keys/private_key.pem
    - keys/public_key.pem
    - images/btn_get.png
    - images/btn_refuse.png
    - images/room_no_listen.png
    - images/room_no_speak.png
    - images/room_save_go.png
    - images/room_go_out.png
    - images/icon_arrow.png
    - images/image_share_room_bg.png
    - images/icon_checkbox.png
    - images/icon_checkbox_on.png
    - assets/audio/voice_call.mp3
    - images/pipei.png
    - images/zudui.png
    - images/room_bg.png
    - images/room_no_people.png
    - images/diaoxian.png
    - images/icon_narrow.png
    - images/icon_qq_login.png
    - images/icon_wx_login.png
    - images/icon_success.png
    - images/icon_login_weibo.png
    - images/icon_game_item_start.png
    - images/icon_game_item_end.png
    - images/qq@3x.png
    - images/qzone@3x.png
    - images/nn@3x.png
    - images/wechat@3x.png
    - images/firend@3x.png
    - images/icon_close.png
    - images/more.png
    - images/icon_search.png
  # To add assets to your application, add an assets section, like this:
    - images/people_icon.png
    - images/chang_room_name.png
    - images/room_right.png
    - images/room_left.png
    - images/boli.png
  # To add assets to your application, add an assets section, like this:go_out_room
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
